language: elixir
sudo: required

services:
  - postgresql

addons:
  postgresql: 9.6

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y postgresql-9.6-postgis-2.4
  - psql -U postgres --command 'CREATE DATABASE cities_test OWNER postgres' -U postgres
  - psql -U postgres --command 'CREATE EXTENSION postgis' --dbname cities_test
  - psql -U postgres --command 'CREATE EXTENSION unaccent' --dbname cities_test
  - psql -U postgres --command 'CREATE EXTENSION pg_trgm' --dbname cities_test
  - psql -U postgres --command "ALTER USER \"postgres\" WITH PASSWORD 'postgres'" -U postgres;
  - mix ecto.migrate

elixir:
  - 1.9.0

otp_release:
  - 22.0

env:
  - MIX_ENV=test

script:
  - mix format --check-formatted
  - mix credo -a
  - mix coveralls.travis
