language: elixir

services:
  - postgresql

before_script:
  - psql -U postgres --command 'CREATE DATABASE cities_test OWNER postgres' -U postgres
  - psql -U postgres --command 'CREATE EXTENSION postgis' --dbname cities_test
  - psql -U postgres --command "ALTER USER \"postgres\" WITH PASSWORD 'postgres'" -U postgres;
  - mix ecto.migrate

elixir:
  - 1.6.0

otp_release:
  - 20.0

env:
  - MIX_ENV=test

script: mix coveralls.travis
